---
# tasks file for install boundary on Linux and Unix system

- name: Linux/Unix | Find all versions of Hashicorp Boundary
  ansible.builtin.uri:
    url: https://releases.hashicorp.com/boundary/index.json
    return_content: true
  register: boundary_index
  when: boundary_cli_version == "latest"
  check_mode: no

- name: Linux/Unix | Finds the latest Boundary version when latest var is define
  ansible.builtin.set_fact:
    boundary_cli_version_to_install: "{{ (boundary_index.content | from_json).versions | reject('search', '-') | list | sort_versions | last }}"
  when: boundary_cli_version == 'latest'

- name: Linux/Unix | Use the specified Boundary version when latest var is not define
  ansible.builtin.set_fact:
    boundary_cli_version_to_install: "{{ boundary_cli_version }}"
  when: boundary_cli_version != 'latest'

- name: Linux/Unix | Install Boundary
  ansible.builtin.unarchive:
    src: "{{ boundary_cli_pkg_url }}"
    dest: "{{ boundary_cli_bin_directory }}"
    remote_src: yes
