---
# tasks file for install boundary on Windows system

- name: Windows | Find all versions of Boundary
  ansible.windows.win_uri:
    url: https://releases.hashicorp.com/boundary/index.json
    return_content: true
    headers:
      user-agent: Mozilla/5.0
  register: boundary_index
  when: boundary_cli_version == 'latest'
  check_mode: no

- name: Windows | Finds the latest Boundary version when latest var is define
  ansible.builtin.set_fact:
    boundary_cli_version_to_install: "{{ (boundary_index.content | from_json).versions | reject('search', '-') | list | sort_versions | last }}"
  when: boundary_cli_version == 'latest'

- name: Windows | Use the specified Boundary version when latest var is not define
  ansible.builtin.set_fact:
    boundary_cli_version_to_install: "{{ boundary_cli_version }}"
  when: boundary_cli_version != 'latest'

- name: Windows | Download Boundary
  ansible.windows.win_get_url:
    url: "{{ boundary_cli_pkg_url }}"
    dest: '%TEMP%\boundary_{{ boundary_cli_version_to_install }}_windows_amd64.zip'
  register: boundary_cli_download

- name: Windows | Create boundary folder
  ansible.windows.win_file:
    path: "{{ boundary_cli_bin_directory }}"
    state: directory

- name: Windows | Install Boundary
  community.windows.win_unzip:
    src: "{{ boundary_cli_download.dest }}"
    dest: "{{ boundary_cli_bin_directory }}"

- name: Windows | Add Boundary to PATH
  ansible.windows.win_path:
    elements: "{{ boundary_cli_bin_directory }}"
