---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-boundary-client"
      include_role:
        name: "ansible-role-boundary-client"
      vars:
        boundary_cli_version: "{{ lookup('env', 'boundary_cli_version') | default('latest', true) }}"
