---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | boundary should be functionnal
      ansible.windows.win_command: boundary version
      register: boundary_result

    - name: Windows | Verify commands outputs
      assert:
        that:
          - boundary_result.rc == 0
        success_msg: "All tests passed"
      when: lookup('env', 'boundary_version') == "latest"

    - name: Windows | Verify commands outputs
      assert:
        that:
          - boundary_result.rc == 0
          - lookup('env', 'boundary_version') in boundary_result.stdout
        success_msg: "All tests passed"
      when: lookup('env', 'boundary_version') != "latest"
