name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.image }} boundary ${{ matrix.waypoint_version }}
    runs-on: ubuntu-22.04
    env:
      docker_namepsace: ghcr.io/diodonfrost/docker-ansible
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux:8
          - rockylinux:8
          - fedora:38
          - ubuntu:22.04
          - debian:11
          - debian:10
          - oraclelinux:9
          - amazonlinux:2
          - opensuse:leap
          - opensuse:tumbleweed
          - archlinux:latest
          - alpine:latest
          - gentoo:latest
        waypoint_version:
          - latest
          - 0.13.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test Ansible role
        run: molecule test
        env:
          namespace: ${{ env.docker_namepsace }}
          image: ansible-${{ matrix.image }}
          waypoint_version: ${{ matrix.waypoint_version }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          namespace: ${{ env.docker_namepsace }}
          image: ansible-${{ matrix.image }}
          waypoint_version: ${{ matrix.waypoint_version }}
